converted/Afghanistan_VII.DHS.VII.women.Rout: downloaded/afir70fl.sav
converted/Afghanistan_VII.DHS.VII.men.Rout: downloaded/afmr70fl.sav
converted/Afghanistan_VII.DHS.VII.cr.Rout: downloaded/afcr70fl.sav
converted/Albania_V.DHS.V.women.Rout: downloaded/alir50fl.sav
converted/Albania_V.DHS.V.men.Rout: downloaded/almr50fl.sav
converted/Albania_V.DHS.V.cr.Rout: downloaded/alcr50fl.sav
converted/Albania_V.DHS.V.gps.Rout: downloaded/alge51fl.dbf
converted/Armenia_IV.DHS.IV.women.Rout: downloaded/amir42fl.sav
converted/Armenia_IV.DHS.IV.men.Rout: downloaded/ammr41fl.sav
converted/Armenia_IV.DHS.IV.cr.Rout: downloaded/amcr42fl.sav
converted/Armenia_V.DHS.IV.women.Rout: downloaded/amir54fl.sav
converted/Armenia_V.DHS.IV.men.Rout: downloaded/ammr52fl.sav
converted/Armenia_V.DHS.IV.cr.Rout: downloaded/amcr52fl.sav
converted/Armenia_VI.DHS.VI.women.Rout: downloaded/amir61fl.sav
converted/Armenia_VI.DHS.VI.men.Rout: downloaded/ammr61fl.sav
converted/Armenia_VI.DHS.VI.cr.Rout: downloaded/amcr61fl.sav
converted/Armenia_VI.DHS.VI.gps.Rout: downloaded/amge61fl.dbf
converted/Azerbaijan_V.DHS.V.women.Rout: downloaded/azir52fl.sav
converted/Azerbaijan_V.DHS.V.men.Rout: downloaded/azmr52fl.sav
converted/Azerbaijan_V.DHS.V.cr.Rout: downloaded/azcr52fl.sav
converted/Bangladesh_IIIb.DHS.III.women.Rout: downloaded/bdir31fl.sav
converted/Bangladesh_IIIb.DHS.III.men.Rout: downloaded/bdmr31fl.sav
converted/Bangladesh_IIIb.DHS.III.cr.Rout: downloaded/bdcr31fl.sav
converted/Bangladesh_IIIa.DHS.III.women.Rout: downloaded/bdir3afl.sav
converted/Bangladesh_IIIa.DHS.III.men.Rout: downloaded/bdmr3afl.sav
converted/Bangladesh_IIIa.DHS.III.cr.Rout: downloaded/bdcr3afl.sav
converted/Bangladesh_IV.DHS.III.women.Rout: downloaded/bdir41fl.sav
converted/Bangladesh_IV.DHS.III.men.Rout: downloaded/bdmr41fl.sav
converted/Bangladesh_IV.DHS.III.cr.Rout: downloaded/bdcr41fl.sav
converted/Bangladesh_IV.DHS.III.gps.Rout: downloaded/bdge42fl.dbf
converted/Bangladesh_IV.DHS.IV.women.Rout: downloaded/bdir4jfl.sav
converted/Bangladesh_IV.DHS.IV.men.Rout: downloaded/bdmr4jfl.sav
converted/Bangladesh_IV.DHS.IV.cr.Rout: downloaded/bdcr4jfl.sav
converted/Bangladesh_IV.DHS.IV.gps.Rout: downloaded/bdge4jfl.dbf
converted/Bangladesh_V.DHS.V.women.Rout: downloaded/bdir51fl.sav
converted/Bangladesh_V.DHS.V.men.Rout: downloaded/bdmr51fl.sav
converted/Bangladesh_V.DHS.V.cr.Rout: downloaded/bdcr51fl.sav
converted/Bangladesh_V.DHS.V.gps.Rout: downloaded/bdge52fl.dbf
converted/Bangladesh_VI.DHS.VI.women.Rout: downloaded/bdir61fl.sav
converted/Bangladesh_VI.DHS.VI.men.Rout: downloaded/bdmr61fl.sav
converted/Bangladesh_VI.DHS.VI.cr.Rout: downloaded/bdcr61fl.sav
converted/Bangladesh_VI.DHS.VI.gps.Rout: downloaded/bdge61fl.dbf
converted/Bangladesh_VII.DHS.VI.women.Rout: downloaded/bdir70fl.sav
converted/Bangladesh_VII.DHS.VI.gps.Rout: downloaded/bdge71fl.dbf
converted/Benin_III.DHS.III.women.Rout: downloaded/bjir31fl.sav
converted/Benin_III.DHS.III.men.Rout: downloaded/bjmr31fl.sav
converted/Benin_III.DHS.III.cr.Rout: downloaded/bjcr31fl.sav
converted/Benin_III.DHS.III.gps.Rout: downloaded/bjge33fl.dbf
converted/Benin_IV.DHS.IV.women.Rout: downloaded/bjir41fl.sav
converted/Benin_IV.DHS.IV.men.Rout: downloaded/bjmr41fl.sav
converted/Benin_IV.DHS.IV.cr.Rout: downloaded/bjcr41fl.sav
converted/Benin_IV.DHS.IV.gps.Rout: downloaded/bjge42fl.dbf
converted/Benin_V.DHS.V.women.Rout: downloaded/bjir51fl.sav
converted/Benin_V.DHS.V.men.Rout: downloaded/bjmr51fl.sav
converted/Benin_V.DHS.V.cr.Rout: downloaded/bjcr51fl.sav
converted/Benin_VI.DHS.VI.women.Rout: downloaded/bjir61fl.sav
converted/Benin_VI.DHS.VI.men.Rout: downloaded/bjmr61fl.sav
converted/Benin_VI.DHS.VI.cr.Rout: downloaded/bjcr61fl.sav
converted/Benin_VI.DHS.VI.gps.Rout: downloaded/bjge61fl.dbf
converted/Bolivia_I.DHS.I.women.Rout: downloaded/boir01fl.sav
converted/Bolivia_IIIb.DHS.III.women.Rout: downloaded/boiq33..boir31fl.sav
converted/Bolivia_IIIa.DHS.III.women.Rout: downloaded/boir3bfl.sav
converted/Bolivia_IIIa.DHS.III.men.Rout: downloaded/bomr3bfl.sav
converted/Bolivia_IIIa.DHS.III.cr.Rout: downloaded/bocr3bfl.sav
converted/Bolivia_IV.DHS.IV.women.Rout: downloaded/boir41fl.sav
converted/Bolivia_IV.DHS.IV.men.Rout: downloaded/bomr41fl.sav
converted/Bolivia_IV.DHS.IV.cr.Rout: downloaded/bocr41fl.sav
converted/Bolivia_V.DHS.V.women.Rout: downloaded/boir51fl.sav
converted/Bolivia_V.DHS.V.men.Rout: downloaded/bomr51fl.sav
converted/Bolivia_V.DHS.V.cr.Rout: downloaded/bocr51fl.sav
converted/Bolivia_V.DHS.V.gps.Rout: downloaded/boge53fl.dbf
converted/Brazil_I.DHS.I.women.Rout: downloaded/brir01fl.sav
converted/Brazil_II.DHS.II.women.Rout: downloaded/brir21fl.sav
converted/Brazil_III.DHS.III.women.Rout: downloaded/brir31fl.sav
converted/Brazil_III.DHS.III.men.Rout: downloaded/brmr31fl.sav
converted/Brazil_III.DHS.III.cr.Rout: downloaded/brcr31fl.sav
converted/Burkina_Faso_II.DHS.II.women.Rout: downloaded/bfir21fl.sav
converted/Burkina_Faso_II.DHS.II.men.Rout: downloaded/bfmr21fl.sav
converted/Burkina_Faso_II.DHS.II.cr.Rout: downloaded/bfcr21fl.sav
converted/Burkina_Faso_II.DHS.II.gps.Rout: downloaded/bfge23fl.dbf
converted/Burkina_Faso_III.DHS.III.women.Rout: downloaded/bfir31fl.sav
converted/Burkina_Faso_III.DHS.III.men.Rout: downloaded/bfmr31fl.sav
converted/Burkina_Faso_III.DHS.III.cr.Rout: downloaded/bfcr31fl.sav
converted/Burkina_Faso_III.DHS.III.gps.Rout: downloaded/bfge32fl.dbf
converted/Burkina_Faso_IV.DHS.IV.women.Rout: downloaded/bfir43fl.sav
converted/Burkina_Faso_IV.DHS.IV.men.Rout: downloaded/bfmr41fl.sav
converted/Burkina_Faso_IV.DHS.IV.cr.Rout: downloaded/bfcr41fl.sav
converted/Burkina_Faso_IV.DHS.IV.gps.Rout: downloaded/bfge43fl.dbf
converted/Burkina_Faso_VI.DHS.VI.women.Rout: downloaded/bfir62fl.sav
converted/Burkina_Faso_VI.DHS.VI.men.Rout: downloaded/bfmr62fl.sav
converted/Burkina_Faso_VI.DHS.VI.cr.Rout: downloaded/bfcr62fl.sav
converted/Burkina_Faso_VI.DHS.VI.gps.Rout: downloaded/bfge61fl.dbf
converted/Burundi_I.DHS.I.women.Rout: downloaded/buir02fl.sav
converted/Burundi_VI.DHS.VI.women.Rout: downloaded/buir61fl.sav
converted/Burundi_VI.DHS.VI.men.Rout: downloaded/bumr61fl.sav
converted/Burundi_VI.DHS.VI.cr.Rout: downloaded/bucr61fl.sav
converted/Burundi_VI.DHS.VI.gps.Rout: downloaded/buge61fl.dbf
converted/Cambodia_IV.DHS.IV.women.Rout: downloaded/khir42fl.sav
converted/Cambodia_IV.DHS.IV.gps.Rout: downloaded/khge43fl.dbf
converted/Cambodia_V.DHS.V.women.Rout: downloaded/khir51fl.sav
converted/Cambodia_V.DHS.V.men.Rout: downloaded/khmr51fl.sav
converted/Cambodia_V.DHS.V.cr.Rout: downloaded/khcr51fl.sav
converted/Cambodia_V.DHS.V.gps.Rout: downloaded/khge51fl.dbf
converted/Cambodia_VI.DHS.V.women.Rout: downloaded/khir61fl.sav
converted/Cambodia_VI.DHS.V.men.Rout: downloaded/khmr61fl.sav
converted/Cambodia_VI.DHS.V.gps.Rout: downloaded/khge62fl.dbf
converted/Cambodia_VII.DHS.VI.women.Rout: downloaded/khir72fl.sav
converted/Cambodia_VII.DHS.VI.men.Rout: downloaded/khmr72fl.sav
converted/Cambodia_VII.DHS.VI.cr.Rout: downloaded/khcr72fl.sav
converted/Cambodia_VII.DHS.VI.gps.Rout: downloaded/khge71fl.dbf
converted/Cameroon_II.DHS.II.women.Rout: downloaded/cmir22fl.sav
converted/Cameroon_II.DHS.II.men.Rout: downloaded/cmmr21fl.sav
converted/Cameroon_II.DHS.II.cr.Rout: downloaded/cmcr21fl.sav
converted/Cameroon_II.DHS.II.gps.Rout: downloaded/cmge23fl.dbf
converted/Cameroon_III.DHS.III.women.Rout: downloaded/cmir31fl.sav
converted/Cameroon_III.DHS.III.men.Rout: downloaded/cmmr31fl.sav
converted/Cameroon_III.DHS.III.cr.Rout: downloaded/cmcr31fl.sav
converted/Cameroon_IV.DHS.IV.women.Rout: downloaded/cmir44fl.sav
converted/Cameroon_IV.DHS.IV.men.Rout: downloaded/cmmr44fl.sav
converted/Cameroon_IV.DHS.IV.cr.Rout: downloaded/cmcr44fl.sav
converted/Cameroon_IV.DHS.IV.gps.Rout: downloaded/cmge42fl.dbf
converted/Cameroon_VI.DHS.VI.women.Rout: downloaded/cmir61fl.sav
converted/Cameroon_VI.DHS.VI.men.Rout: downloaded/cmmr61fl.sav
converted/Cameroon_VI.DHS.VI.cr.Rout: downloaded/cmcr61fl.sav
converted/Cameroon_VI.DHS.VI.gps.Rout: downloaded/cmge61fl.dbf
converted/Central_African_Republic_III.DHS.III.women.Rout: downloaded/cfir31fl.sav
converted/Central_African_Republic_III.DHS.III.men.Rout: downloaded/cfmr31fl.sav
converted/Central_African_Republic_III.DHS.III.cr.Rout: downloaded/cfcr31fl.sav
converted/Central_African_Republic_III.DHS.III.gps.Rout: downloaded/cfge33fl.dbf
converted/Chad_III.DHS.III.women.Rout: downloaded/tdir31fl.sav
converted/Chad_III.DHS.III.men.Rout: downloaded/tdmr31fl.sav
converted/Chad_III.DHS.III.cr.Rout: downloaded/tdcr31fl.sav
converted/Chad_IV.DHS.IV.women.Rout: downloaded/tdir41fl.sav
converted/Chad_IV.DHS.IV.men.Rout: downloaded/tdmr41fl.sav
converted/Chad_IV.DHS.IV.cr.Rout: downloaded/tdcr41fl.sav
converted/Chad_VII.DHS.VI.women.Rout: downloaded/tdir71fl.sav
converted/Chad_VII.DHS.VI.men.Rout: downloaded/tdmr71fl.sav
converted/Chad_VII.DHS.VI.cr.Rout: downloaded/tdcr71fl.sav
converted/Chad_VII.DHS.VI.gps.Rout: downloaded/tdge71fl.dbf
converted/Colombia_I.DHS.I.women.Rout: downloaded/coir01fl.sav
converted/Colombia_II.DHS.II.women.Rout: downloaded/coir22fl.sav
converted/Colombia_III.DHS.III.women.Rout: downloaded/coir31fl.sav
converted/Colombia_IV.DHS.IV.women.Rout: downloaded/coir41fl.sav
converted/Colombia_V.DHS.IV.women.Rout: downloaded/coir53fl.sav
converted/Colombia_VI.DHS.V.women.Rout: downloaded/coir61fl.sav
converted/Colombia_VI.DHS.V.gps.Rout: downloaded/coge61fl.dbf
converted/Comoros_III.DHS.III.women.Rout: downloaded/kmir32fl.sav
converted/Comoros_III.DHS.III.men.Rout: downloaded/kmmr31fl.sav
converted/Comoros_III.DHS.III.cr.Rout: downloaded/kmcr31fl.sav
converted/Comoros_VI.DHS.VI.women.Rout: downloaded/kmir61fl.sav
converted/Comoros_VI.DHS.VI.men.Rout: downloaded/kmmr61fl.sav
converted/Comoros_VI.DHS.VI.cr.Rout: downloaded/kmcr61fl.sav
converted/Comoros_VI.DHS.VI.gps.Rout: downloaded/kmge61fl.dbf
converted/Congo_Brazzaville_V.DHS.V.women.Rout: downloaded/cgir51fl.sav
converted/Congo_Brazzaville_V.DHS.V.men.Rout: downloaded/cgmr51fl.sav
converted/Congo_Brazzaville_V.DHS.V.cr.Rout: downloaded/cgcr51fl.sav
converted/Congo_Brazzaville_V.AIS.V.women.Rout: downloaded/cgir5hfl.sav
converted/Congo_Brazzaville_VI.DHS.VI.women.Rout: downloaded/cgir60fl.sav
converted/Congo_Brazzaville_VI.DHS.VI.men.Rout: downloaded/cgmr60fl.sav
converted/Congo_Brazzaville_VI.DHS.VI.cr.Rout: downloaded/cgcr60fl.sav
converted/Congo_Kinshasa_V.DHS.V.women.Rout: downloaded/cdir50fl.sav
converted/Congo_Kinshasa_V.DHS.V.men.Rout: downloaded/cdmr50fl.sav
converted/Congo_Kinshasa_V.DHS.V.cr.Rout: downloaded/cdcr50fl.sav
converted/Congo_Kinshasa_V.DHS.V.gps.Rout: downloaded/cdge52fl.dbf
converted/Congo_Kinshasa_VI.DHS.VI.women.Rout: downloaded/cdir61fl.sav
converted/Congo_Kinshasa_VI.DHS.VI.men.Rout: downloaded/cdmr61fl.sav
converted/Congo_Kinshasa_VI.DHS.VI.cr.Rout: downloaded/cdcr61fl.sav
converted/Congo_Kinshasa_VI.DHS.VI.gps.Rout: downloaded/cdge61fl.dbf
converted/Dominican_Republic_I.DHS.I.women.Rout: downloaded/drir01fl.sav
converted/Dominican_Republic_II.DHS.II.women.Rout: downloaded/drir21fl.sav
converted/Dominican_Republic_III.DHS.III.women.Rout: downloaded/drir32fl.sav
converted/Dominican_Republic_III.DHS.III.men.Rout: downloaded/drmr31fl.sav
converted/Dominican_Republic_III.DHS.III.cr.Rout: downloaded/drcr31fl.sav
converted/Dominican_Republic_IVb.DHS.IV.women.Rout: downloaded/drir41fl.sav
converted/Dominican_Republic_IVb.DHS.IV.men.Rout: downloaded/drmr41fl.sav
converted/Dominican_Republic_IVb.DHS.IV.cr.Rout: downloaded/drcr41fl.sav
converted/Dominican_Republic_IVa.DHS.IV.women.Rout: downloaded/drir4afl.sav
converted/Dominican_Republic_IVa.DHS.IV.men.Rout: downloaded/drmr4afl.sav
converted/Dominican_Republic_IVa.DHS.IV.cr.Rout: downloaded/drcr4afl.sav
converted/Dominican_Republic_V.DHS.V.women.Rout: downloaded/drir52fl.sav
converted/Dominican_Republic_V.DHS.V.men.Rout: downloaded/drmr52fl.sav
converted/Dominican_Republic_V.DHS.V.cr.Rout: downloaded/drcr52fl.sav
converted/Dominican_Republic_V.DHS.V.gps.Rout: downloaded/drge52fl.dbf
converted/Dominican_Republic_VI.DHS.VI.women.Rout: downloaded/drir61fl.sav
converted/Dominican_Republic_VI.DHS.VI.men.Rout: downloaded/drmr61fl.sav
converted/Dominican_Republic_VI.DHS.VI.cr.Rout: downloaded/drcr61fl.sav
converted/Dominican_Republic_VI.DHS.VI.gps.Rout: downloaded/drge61fl.dbf
converted/Ecuador_I.DHS.I.women.Rout: downloaded/ecir01fl.sav
converted/Egypt_I.DHS.I.women.Rout: downloaded/egir01fl.sav
converted/Egypt_II.DHS.II.women.Rout: downloaded/egir21fl.sav
converted/Egypt_II.DHS.II.gps.Rout: downloaded/egge22fl.dbf
converted/Egypt_III.DHS.III.women.Rout: downloaded/egws39..egir33fl.sav
converted/Egypt_III.DHS.III.gps.Rout: downloaded/egge32fl.dbf
converted/Egypt_IV.DHS.IV.women.Rout: downloaded/egir42fl.sav
converted/Egypt_IV.DHS.IV.gps.Rout: downloaded/egge42fl.dbf
converted/Egypt_V.DHS.IV.women.Rout: downloaded/egir51fl.sav
converted/Egypt_V.DHS.IV.gps.Rout: downloaded/egge52fl.dbf
converted/Egypt_V.DHS.V.women.Rout: downloaded/egir5a..egiq5afl.sav
converted/Egypt_V.DHS.V.gps.Rout: downloaded/egge5d..egob5afl.dbf
converted/Egypt_VI.DHS.VI.women.Rout: downloaded/egir61fl.sav
converted/Egypt_VI.DHS.VI.gps.Rout: downloaded/egge61fl.dbf
converted/El_Salvador_I.DHS.I.women.Rout: downloaded/esir01fl.sav
converted/Ethiopia_IV.DHS.IV.women.Rout: downloaded/etir41fl.sav
converted/Ethiopia_IV.DHS.IV.men.Rout: downloaded/etmr41fl.sav
converted/Ethiopia_IV.DHS.IV.cr.Rout: downloaded/etcr41fl.sav
converted/Ethiopia_IV.DHS.IV.gps.Rout: downloaded/etge42fl.dbf
converted/Ethiopia_V.DHS.IV.women.Rout: downloaded/etir51fl.sav
converted/Ethiopia_V.DHS.IV.men.Rout: downloaded/etmr51fl.sav
converted/Ethiopia_V.DHS.IV.cr.Rout: downloaded/etcr51fl.sav
converted/Ethiopia_V.DHS.IV.gps.Rout: downloaded/etge52fl.dbf
converted/Ethiopia_VI.DHS.VI.women.Rout: downloaded/etir61fl.sav
converted/Ethiopia_VI.DHS.VI.men.Rout: downloaded/etmr61fl.sav
converted/Ethiopia_VI.DHS.VI.cr.Rout: downloaded/etcr61fl.sav
converted/Ethiopia_VI.DHS.VI.gps.Rout: downloaded/etge61fl.dbf
converted/Gabon_IV.DHS.III.women.Rout: downloaded/gair41fl.sav
converted/Gabon_IV.DHS.III.men.Rout: downloaded/gamr41fl.sav
converted/Gabon_IV.DHS.III.cr.Rout: downloaded/gacr41fl.sav
converted/Gabon_VI.DHS.VI.women.Rout: downloaded/gair60fl.sav
converted/Gabon_VI.DHS.VI.men.Rout: downloaded/gamr60fl.sav
converted/Gabon_VI.DHS.VI.cr.Rout: downloaded/gacr60fl.sav
converted/Gabon_VI.DHS.VI.gps.Rout: downloaded/gage61fl.dbf
converted/Gambia_VI.DHS.VI.women.Rout: downloaded/gmir60fl.sav
converted/Gambia_VI.DHS.VI.men.Rout: downloaded/gmmr60fl.sav
converted/Gambia_VI.DHS.VI.cr.Rout: downloaded/gmcr60fl.sav
converted/Ghana_I.DHS.I.women.Rout: downloaded/ghir02fl.sav
converted/Ghana_III.DHS.II.women.Rout: downloaded/ghir31fl.sav
converted/Ghana_III.DHS.II.men.Rout: downloaded/ghmr31fl.sav
converted/Ghana_III.DHS.II.cr.Rout: downloaded/ghcr31fl.sav
converted/Ghana_III.DHS.II.gps.Rout: downloaded/ghge33fl.dbf
converted/Ghana_IV.DHS.III.women.Rout: downloaded/ghir41fl.sav
converted/Ghana_IV.DHS.III.men.Rout: downloaded/ghmr41fl.sav
converted/Ghana_IV.DHS.III.cr.Rout: downloaded/ghcr41fl.sav
converted/Ghana_IV.DHS.III.gps.Rout: downloaded/ghge42fl.dbf
converted/Ghana_IV.DHS.IV.women.Rout: downloaded/ghir4bfl.sav
converted/Ghana_IV.DHS.IV.men.Rout: downloaded/ghmr4bfl.sav
converted/Ghana_IV.DHS.IV.cr.Rout: downloaded/ghcr4bfl.sav
converted/Ghana_IV.DHS.IV.gps.Rout: downloaded/ghge4bfl.dbf
converted/Ghana_V.DHS.V.women.Rout: downloaded/ghir5afl.sav
converted/Ghana_V.DHS.V.men.Rout: downloaded/ghmr5afl.sav
converted/Ghana_V.DHS.V.cr.Rout: downloaded/ghcr5afl.sav
converted/Ghana_V.DHS.V.gps.Rout: downloaded/ghge5afl.dbf
converted/Ghana_VII.DHS.VI.women.Rout: downloaded/ghir72fl.sav
converted/Ghana_VII.DHS.VI.men.Rout: downloaded/ghmr71fl.sav
converted/Ghana_VII.DHS.VI.cr.Rout: downloaded/ghcr71fl.sav
converted/Ghana_VII.DHS.VI.gps.Rout: downloaded/ghge71fl.dbf
converted/Guatemala_I.DHS.I.women.Rout: downloaded/guir01fl.sav
converted/Guatemala_III.DHS.III.women.Rout: downloaded/guir34fl.sav
converted/Guatemala_VII.DHS.VI.women.Rout: downloaded/guir71fl.sav
converted/Guatemala_VII.DHS.VI.men.Rout: downloaded/gumr71fl.sav
converted/Guatemala_VII.DHS.VI.gps.Rout: downloaded/guge71fl.dbf
converted/Guinea_IV.DHS.III.women.Rout: downloaded/gnir41fl.sav
converted/Guinea_IV.DHS.III.men.Rout: downloaded/gnmr41fl.sav
converted/Guinea_IV.DHS.III.cr.Rout: downloaded/gncr41fl.sav
converted/Guinea_IV.DHS.III.gps.Rout: downloaded/gnge42fl.dbf
converted/Guinea_V.DHS.IV.women.Rout: downloaded/gnir52fl.sav
converted/Guinea_V.DHS.IV.men.Rout: downloaded/gnmr52fl.sav
converted/Guinea_V.DHS.IV.cr.Rout: downloaded/gncr52fl.sav
converted/Guinea_V.DHS.IV.gps.Rout: downloaded/gnge52fl.dbf
converted/Guinea_VI.DHS.VI.women.Rout: downloaded/gnir61fl.sav
converted/Guinea_VI.DHS.VI.men.Rout: downloaded/gnmr61fl.sav
converted/Guinea_VI.DHS.VI.cr.Rout: downloaded/gncr61fl.sav
converted/Guinea_VI.DHS.VI.gps.Rout: downloaded/gnge61fl.dbf
converted/Guyana_V.AIS.V.women.Rout: downloaded/gyir51fl.sav
converted/Guyana_V.DHS.V.women.Rout: downloaded/gyir5ifl.sav
converted/Guyana_V.DHS.V.men.Rout: downloaded/gymr5ifl.sav
converted/Guyana_V.DHS.V.cr.Rout: downloaded/gycr5ifl.sav
converted/Guyana_V.DHS.V.gps.Rout: downloaded/gyge5jfl.dbf
converted/Haiti_III.DHS.III.women.Rout: downloaded/htir31fl.sav
converted/Haiti_III.DHS.III.men.Rout: downloaded/htmr31fl.sav
converted/Haiti_III.DHS.III.cr.Rout: downloaded/htcr31fl.sav
converted/Haiti_IV.DHS.IV.women.Rout: downloaded/htir42fl.sav
converted/Haiti_IV.DHS.IV.men.Rout: downloaded/htmr42fl.sav
converted/Haiti_IV.DHS.IV.cr.Rout: downloaded/htcr42fl.sav
converted/Haiti_IV.DHS.IV.gps.Rout: downloaded/htge42fl.dbf
converted/Haiti_V.DHS.V.women.Rout: downloaded/htir52fl.sav
converted/Haiti_V.DHS.V.men.Rout: downloaded/htmr52fl.sav
converted/Haiti_V.DHS.V.cr.Rout: downloaded/htcr52fl.sav
converted/Haiti_V.DHS.V.gps.Rout: downloaded/htge52fl.dbf
converted/Haiti_VI.DHS.VI.women.Rout: downloaded/htir61fl.sav
converted/Haiti_VI.DHS.VI.men.Rout: downloaded/htmr61fl.sav
converted/Haiti_VI.DHS.VI.cr.Rout: downloaded/htcr61fl.sav
converted/Haiti_VI.DHS.VI.gps.Rout: downloaded/htge61fl.dbf
converted/Honduras_V.DHS.V.women.Rout: downloaded/hnir52fl.sav
converted/Honduras_VI.DHS.VI.women.Rout: downloaded/hnir62fl.sav
converted/Honduras_VI.DHS.VI.men.Rout: downloaded/hnmr62fl.sav
converted/Honduras_VI.DHS.VI.gps.Rout: downloaded/hnge61fl.dbf
converted/Indonesia_I.DHS.I.women.Rout: downloaded/idir01fl.sav
converted/Indonesia_II.DHS.II.women.Rout: downloaded/idir21fl.sav
converted/Indonesia_IIIb.DHS.III.women.Rout: downloaded/idir31fl.sav
converted/Indonesia_IIIa.DHS.III.women.Rout: downloaded/idir3afl.sav
converted/Indonesia_IV.DHS.IV.women.Rout: downloaded/idir42fl.sav
converted/Indonesia_IV.DHS.IV.men.Rout: downloaded/idmr42fl.sav
converted/Indonesia_IV.DHS.IV.cr.Rout: downloaded/idcr42fl.sav
converted/Indonesia_IV.DHS.IV.gps.Rout: downloaded/idge43fl.dbf
converted/Indonesia_V.DHS.V.women.Rout: downloaded/idir51fl.sav
converted/Indonesia_V.DHS.V.men.Rout: downloaded/idmr51fl.sav
converted/Indonesia_V.DHS.V.cr.Rout: downloaded/idcr51fl.sav
converted/Indonesia_VI.DHS.VI.women.Rout: downloaded/idir63fl.sav
converted/Indonesia_VI.DHS.VI.men.Rout: downloaded/idmr63fl.sav
converted/Indonesia_VI.DHS.VI.cr.Rout: downloaded/idcr63fl.sav
converted/Ivory_Coast_IIIb.DHS.III.women.Rout: downloaded/ciir35fl.sav
converted/Ivory_Coast_IIIb.DHS.III.men.Rout: downloaded/cimr33fl.sav
converted/Ivory_Coast_IIIb.DHS.III.cr.Rout: downloaded/cicr35fl.sav
converted/Ivory_Coast_IIIb.DHS.III.gps.Rout: downloaded/cige33fl.dbf
converted/Ivory_Coast_IIIa.DHS.III.women.Rout: downloaded/ciir3afl.sav
converted/Ivory_Coast_IIIa.DHS.III.men.Rout: downloaded/cimr3afl.sav
converted/Ivory_Coast_IIIa.DHS.III.cr.Rout: downloaded/cicr3afl.sav
converted/Ivory_Coast_IIIa.DHS.III.gps.Rout: downloaded/cige3bfl.dbf
converted/Ivory_Coast_V.AIS.V.women.Rout: downloaded/ciir50fl.sav
converted/Ivory_Coast_VI.DHS.VI.women.Rout: downloaded/ciir61fl.sav
converted/Ivory_Coast_VI.DHS.VI.men.Rout: downloaded/cimr61fl.sav
converted/Ivory_Coast_VI.DHS.VI.cr.Rout: downloaded/cicr61fl.sav
converted/Ivory_Coast_VI.DHS.VI.gps.Rout: downloaded/cige61fl.dbf
converted/Jordan_II.DHS.II.women.Rout: downloaded/joir21fl.sav
converted/Jordan_III.DHS.III.women.Rout: downloaded/joir31fl.sav
converted/Jordan_IV.DHS.IV.women.Rout: downloaded/joir42fl.sav
converted/Jordan_IV.DHS.IV.gps.Rout: downloaded/joge43fl.dbf
converted/Jordan_V.DHS.V.women.Rout: downloaded/joir51fl.sav
converted/Jordan_V.DHS.V.gps.Rout: downloaded/joge52fl.dbf
converted/Jordan_VI.DHS.VI.women.Rout: downloaded/joir6cfl.sav
converted/Jordan_VI.DHS.VI.gps.Rout: downloaded/joge6afl.dbf
converted/Kazakhstan_III.DHS.III.women.Rout: downloaded/kkir31fl.sav
converted/Kazakhstan_IV.DHS.III.women.Rout: downloaded/kkir42fl.sav
converted/Kazakhstan_IV.DHS.III.men.Rout: downloaded/kkmr41fl.sav
converted/Kazakhstan_IV.DHS.III.cr.Rout: downloaded/kkcr42fl.sav
converted/Kenya_I.DHS.I.women.Rout: downloaded/keir03fl.sav
converted/Kenya_III.DHS.II.women.Rout: downloaded/keir33fl.sav
converted/Kenya_III.DHS.II.men.Rout: downloaded/kemr32fl.sav
converted/Kenya_III.DHS.II.cr.Rout: downloaded/kecr32fl.sav
converted/Kenya_III.DHS.III.women.Rout: downloaded/keir3afl.sav
converted/Kenya_III.DHS.III.men.Rout: downloaded/kemr3afl.sav
converted/Kenya_III.DHS.III.cr.Rout: downloaded/kecr3afl.sav
converted/Kenya_IV.DHS.IV.women.Rout: downloaded/keir42fl.sav
converted/Kenya_IV.DHS.IV.men.Rout: downloaded/kemr42fl.sav
converted/Kenya_IV.DHS.IV.cr.Rout: downloaded/kecr42fl.sav
converted/Kenya_IV.DHS.IV.gps.Rout: downloaded/kege43fl.dbf
converted/Kenya_V.DHS.V.women.Rout: downloaded/keir52fl.sav
converted/Kenya_V.DHS.V.men.Rout: downloaded/kemr52fl.sav
converted/Kenya_V.DHS.V.cr.Rout: downloaded/kecr52fl.sav
converted/Kenya_V.DHS.V.gps.Rout: downloaded/kege52fl.dbf
converted/Kenya_VII.DHS.VI.women.Rout: downloaded/keir70fl.sav
converted/Kenya_VII.DHS.VI.men.Rout: downloaded/kemr70fl.sav
converted/Kenya_VII.DHS.VI.cr.Rout: downloaded/kecr70fl.sav
converted/Kenya_VII.DHS.VI.gps.Rout: downloaded/kege71fl.dbf
converted/Kyrgyzstan_III.DHS.III.women.Rout: downloaded/kyir31fl.sav
converted/Kyrgyzstan_VI.DHS.VI.women.Rout: downloaded/kyir61fl.sav
converted/Kyrgyzstan_VI.DHS.VI.men.Rout: downloaded/kymr61fl.sav
converted/Kyrgyzstan_VI.DHS.VI.cr.Rout: downloaded/kycr61fl.sav
converted/Kyrgyzstan_VI.DHS.VI.gps.Rout: downloaded/kyge61fl.dbf
converted/Lesotho_IV.DHS.IV.women.Rout: downloaded/lsir41fl.sav
converted/Lesotho_IV.DHS.IV.men.Rout: downloaded/lsmr41fl.sav
converted/Lesotho_IV.DHS.IV.cr.Rout: downloaded/lscr41fl.sav
converted/Lesotho_IV.DHS.IV.gps.Rout: downloaded/lsge42fl.dbf
converted/Lesotho_VI.DHS.V.women.Rout: downloaded/lsir61fl.sav
converted/Lesotho_VI.DHS.V.men.Rout: downloaded/lsmr61fl.sav
converted/Lesotho_VI.DHS.V.cr.Rout: downloaded/lscr61fl.sav
converted/Lesotho_VI.DHS.V.gps.Rout: downloaded/lsge62fl.dbf
converted/Lesotho_VII.DHS.VI.women.Rout: downloaded/lsir71fl.sav
converted/Lesotho_VII.DHS.VI.men.Rout: downloaded/lsmr71fl.sav
converted/Lesotho_VII.DHS.VI.cr.Rout: downloaded/lscr71fl.sav
converted/Lesotho_VII.DHS.VI.gps.Rout: downloaded/lsge71fl.dbf
converted/Liberia_I.DHS.I.women.Rout: downloaded/lbir01fl.sav
converted/Liberia_I.DHS.I.gps.Rout: downloaded/lbge03fl.dbf
converted/Liberia_V.DHS.V.women.Rout: downloaded/lbir51fl.sav
converted/Liberia_V.DHS.V.men.Rout: downloaded/lbmr51fl.sav
converted/Liberia_V.DHS.V.cr.Rout: downloaded/lbcr51fl.sav
converted/Liberia_V.DHS.V.gps.Rout: downloaded/lbge52fl.dbf
converted/Liberia_VI.DHS.VI.women.Rout: downloaded/lbir6afl.sav
converted/Liberia_VI.DHS.VI.men.Rout: downloaded/lbmr6afl.sav
converted/Liberia_VI.DHS.VI.cr.Rout: downloaded/lbcr6afl.sav
converted/Liberia_VI.DHS.VI.gps.Rout: downloaded/lbge6afl.dbf
converted/Madagascar_II.DHS.II.women.Rout: downloaded/mdir21fl.sav
converted/Madagascar_III.DHS.III.women.Rout: downloaded/mdir31fl.sav
converted/Madagascar_III.DHS.III.gps.Rout: downloaded/mdge32fl.dbf
converted/Madagascar_IV.DHS.IV.women.Rout: downloaded/mdir41fl.sav
converted/Madagascar_IV.DHS.IV.men.Rout: downloaded/mdmr41fl.sav
converted/Madagascar_IV.DHS.IV.cr.Rout: downloaded/mdcr41fl.sav
converted/Madagascar_V.DHS.V.women.Rout: downloaded/mdir51fl.sav
converted/Madagascar_V.DHS.V.men.Rout: downloaded/mdmr51fl.sav
converted/Madagascar_V.DHS.V.cr.Rout: downloaded/mdcr51fl.sav
converted/Madagascar_V.DHS.V.gps.Rout: downloaded/mdge53fl.dbf
converted/Malawi_II.DHS.II.women.Rout: downloaded/mwir22fl.sav
converted/Malawi_II.DHS.II.men.Rout: downloaded/mwmr21fl.sav
converted/Malawi_II.DHS.II.cr.Rout: downloaded/mwcr21fl.sav
converted/Malawi_IVb.DHS.IV.women.Rout: downloaded/mwir41fl.sav
converted/Malawi_IVb.DHS.IV.men.Rout: downloaded/mwmr41fl.sav
converted/Malawi_IVb.DHS.IV.cr.Rout: downloaded/mwcr41fl.sav
converted/Malawi_IVb.DHS.IV.gps.Rout: downloaded/mwge43fl.dbf
converted/Malawi_IVa.DHS.IV.women.Rout: downloaded/mwir4dfl.sav
converted/Malawi_IVa.DHS.IV.men.Rout: downloaded/mwmr4dfl.sav
converted/Malawi_IVa.DHS.IV.cr.Rout: downloaded/mwcr4dfl.sav
converted/Malawi_IVa.DHS.IV.gps.Rout: downloaded/mwge4bfl.dbf
converted/Malawi_VI.DHS.V.women.Rout: downloaded/mwir61fl.sav
converted/Malawi_VI.DHS.V.men.Rout: downloaded/mwmr61fl.sav
converted/Malawi_VI.DHS.V.cr.Rout: downloaded/mwcr61fl.sav
converted/Malawi_VI.DHS.V.gps.Rout: downloaded/mwge62fl.dbf
converted/Malawi_VII.DHS.VII.women.Rout: downloaded/mwir7hfl.sav
converted/Malawi_VII.DHS.VII.men.Rout: downloaded/mwmr7hfl.sav
converted/Malawi_VII.DHS.VII.cr.Rout: downloaded/mwcr7hfl.sav
converted/Malawi_VII.DHS.VII.gps.Rout: downloaded/mwge7afl.dbf
converted/Maldives_V.DHS.V.women.Rout: downloaded/mvir51fl.sav
converted/Maldives_V.DHS.V.men.Rout: downloaded/mvmr51fl.sav
converted/Maldives_V.DHS.V.cr.Rout: downloaded/mvcr51fl.sav
converted/Mali_I.DHS.I.women.Rout: downloaded/mlir01fl.sav
converted/Mali_I.DHS.I.men.Rout: downloaded/mlml01fl.sav
converted/Mali_III.DHS.III.women.Rout: downloaded/mlir32fl.sav
converted/Mali_III.DHS.III.men.Rout: downloaded/mlmr31fl.sav
converted/Mali_III.DHS.III.cr.Rout: downloaded/mlcr31fl.sav
converted/Mali_III.DHS.III.gps.Rout: downloaded/mlge33fl.dbf
converted/Mali_IV.DHS.IV.women.Rout: downloaded/mlir41fl.sav
converted/Mali_IV.DHS.IV.men.Rout: downloaded/mlmr41fl.sav
converted/Mali_IV.DHS.IV.cr.Rout: downloaded/mlcr41fl.sav
converted/Mali_IV.DHS.IV.gps.Rout: downloaded/mlge42fl.dbf
converted/Mali_V.DHS.V.women.Rout: downloaded/mlir53fl.sav
converted/Mali_V.DHS.V.men.Rout: downloaded/mlmr53fl.sav
converted/Mali_V.DHS.V.cr.Rout: downloaded/mlcr53fl.sav
converted/Mali_V.DHS.V.gps.Rout: downloaded/mlge52fl.dbf
converted/Mali_VI.DHS.VI.women.Rout: downloaded/mlir6hfl.sav
converted/Mali_VI.DHS.VI.men.Rout: downloaded/mlmr6hfl.sav
converted/Mali_VI.DHS.VI.cr.Rout: downloaded/mlcr6hfl.sav
converted/Mali_VI.DHS.VI.gps.Rout: downloaded/mlge6afl.dbf
converted/Mexico_I.DHS.I.women.Rout: downloaded/mxir01fl.sav
converted/Moldova_V.DHS.IV.women.Rout: downloaded/mbir53fl.sav
converted/Moldova_V.DHS.IV.men.Rout: downloaded/mbmr52fl.sav
converted/Moldova_V.DHS.IV.cr.Rout: downloaded/mbcr52fl.sav
converted/Moldova_V.DHS.IV.gps.Rout: downloaded/mbge52fl.dbf
converted/Morocco_I.DHS.I.women.Rout: downloaded/mair01fl.sav
converted/Morocco_II.DHS.II.women.Rout: downloaded/mair21fl.sav
converted/Morocco_IV.DHS.IV.women.Rout: downloaded/mair43fl.sav
converted/Morocco_IV.DHS.IV.gps.Rout: downloaded/mage43fl.dbf
converted/Mozambique_III.DHS.III.women.Rout: downloaded/mzir31fl.sav
converted/Mozambique_III.DHS.III.men.Rout: downloaded/mzmr31fl.sav
converted/Mozambique_III.DHS.III.cr.Rout: downloaded/mzcr31fl.sav
converted/Mozambique_IV.DHS.IV.women.Rout: downloaded/mzir41fl.sav
converted/Mozambique_IV.DHS.IV.men.Rout: downloaded/mzmr41fl.sav
converted/Mozambique_IV.DHS.IV.cr.Rout: downloaded/mzcr41fl.sav
converted/Mozambique_V.AIS.V.women.Rout: downloaded/mzir51fl.sav
converted/Mozambique_V.AIS.V.gps.Rout: downloaded/mzge52fl.dbf
converted/Mozambique_VI.DHS.VI.women.Rout: downloaded/mzir62fl.sav
converted/Mozambique_VI.DHS.VI.men.Rout: downloaded/mzmr62fl.sav
converted/Mozambique_VI.DHS.VI.cr.Rout: downloaded/mzcr62fl.sav
converted/Mozambique_VI.DHS.VI.gps.Rout: downloaded/mzge61fl.dbf
converted/Myanmar_VII.DHS.VII.women.Rout: downloaded/mmir71fl.sav
converted/Myanmar_VII.DHS.VII.men.Rout: downloaded/mmmr71fl.sav
converted/Myanmar_VII.DHS.VII.cr.Rout: downloaded/mmcr71fl.sav
converted/Myanmar_VII.DHS.VII.gps.Rout: downloaded/mmge71fl.dbf
converted/Namibia_II.DHS.II.women.Rout: downloaded/nmir21fl.sav
converted/Namibia_IV.DHS.IV.women.Rout: downloaded/nmir41fl.sav
converted/Namibia_IV.DHS.IV.men.Rout: downloaded/nmmr41fl.sav
converted/Namibia_IV.DHS.IV.cr.Rout: downloaded/nmcr41fl.sav
converted/Namibia_IV.DHS.IV.gps.Rout: downloaded/nmge42fl.dbf
converted/Namibia_V.DHS.V.women.Rout: downloaded/nmir51fl.sav
converted/Namibia_V.DHS.V.men.Rout: downloaded/nmmr51fl.sav
converted/Namibia_V.DHS.V.cr.Rout: downloaded/nmcr51fl.sav
converted/Namibia_V.DHS.V.gps.Rout: downloaded/nmge53fl.dbf
converted/Namibia_VI.DHS.VI.women.Rout: downloaded/nmir61fl.sav
converted/Namibia_VI.DHS.VI.men.Rout: downloaded/nmmr61fl.sav
converted/Namibia_VI.DHS.VI.cr.Rout: downloaded/nmcr61fl.sav
converted/Namibia_VI.DHS.VI.gps.Rout: downloaded/nmge61fl.dbf
converted/Nepal_III.DHS.III.women.Rout: downloaded/npir31fl.sav
converted/Nepal_IV.DHS.IV.women.Rout: downloaded/npir41fl.sav
converted/Nepal_IV.DHS.IV.men.Rout: downloaded/npmr41fl.sav
converted/Nepal_IV.DHS.IV.cr.Rout: downloaded/npcr41fl.sav
converted/Nepal_IV.DHS.IV.gps.Rout: downloaded/npge42fl.dbf
converted/Nepal_V.DHS.V.women.Rout: downloaded/npir51fl.sav
converted/Nepal_V.DHS.V.men.Rout: downloaded/npmr51fl.sav
converted/Nepal_V.DHS.V.cr.Rout: downloaded/npcr51fl.sav
converted/Nepal_V.DHS.V.gps.Rout: downloaded/npge53fl.dbf
converted/Nepal_VI.DHS.VI.women.Rout: downloaded/npir60fl.sav
converted/Nepal_VI.DHS.VI.men.Rout: downloaded/npmr60fl.sav
converted/Nepal_VI.DHS.VI.cr.Rout: downloaded/npcr60fl.sav
converted/Nepal_VI.DHS.VI.gps.Rout: downloaded/npge61fl.dbf
converted/Nicaragua_III.DHS.III.women.Rout: downloaded/ncir31fl.sav
converted/Nicaragua_III.DHS.III.men.Rout: downloaded/ncmr31fl.sav
converted/Nicaragua_III.DHS.III.cr.Rout: downloaded/nccr31fl.sav
converted/Nicaragua_IV.DHS.IV.women.Rout: downloaded/ncir41fl.sav
converted/Niger_II.DHS.II.women.Rout: downloaded/niir22fl.sav
converted/Niger_II.DHS.II.men.Rout: downloaded/nimr21fl.sav
converted/Niger_II.DHS.II.cr.Rout: downloaded/nicr21fl.sav
converted/Niger_II.DHS.II.gps.Rout: downloaded/nige23fl.dbf
converted/Niger_III.DHS.III.women.Rout: downloaded/niir31fl.sav
converted/Niger_III.DHS.III.men.Rout: downloaded/nimr31fl.sav
converted/Niger_III.DHS.III.cr.Rout: downloaded/nicr31fl.sav
converted/Niger_III.DHS.III.gps.Rout: downloaded/nige32fl.dbf
converted/Niger_V.DHS.V.women.Rout: downloaded/niir51fl.sav
converted/Niger_V.DHS.V.men.Rout: downloaded/nimr51fl.sav
converted/Niger_V.DHS.V.cr.Rout: downloaded/nicr51fl.sav
converted/Niger_VI.DHS.VI.women.Rout: downloaded/niir61fl.sav
converted/Niger_VI.DHS.VI.men.Rout: downloaded/nimr61fl.sav
converted/Niger_VI.DHS.VI.cr.Rout: downloaded/nicr61fl.sav
converted/Nigeria_II.DHS.II.women.Rout: downloaded/ngir21fl.sav
converted/Nigeria_II.DHS.II.gps.Rout: downloaded/ngge23fl.dbf
converted/Nigeria_IVa.DHS.IV.women.Rout: downloaded/ngir4bfl.sav
converted/Nigeria_IVa.DHS.IV.men.Rout: downloaded/ngmr4afl.sav
converted/Nigeria_IVa.DHS.IV.cr.Rout: downloaded/ngcr4afl.sav
converted/Nigeria_IVa.DHS.IV.gps.Rout: downloaded/ngge4bfl.dbf
converted/Nigeria_V.DHS.V.women.Rout: downloaded/ngir53fl.sav
converted/Nigeria_V.DHS.V.men.Rout: downloaded/ngmr52fl.sav
converted/Nigeria_V.DHS.V.cr.Rout: downloaded/ngcr53fl.sav
converted/Nigeria_V.DHS.V.gps.Rout: downloaded/ngge52fl.dbf
converted/Nigeria_VI.DHS.VI.women.Rout: downloaded/ngir6afl.sav
converted/Nigeria_VI.DHS.VI.men.Rout: downloaded/ngmr6afl.sav
converted/Nigeria_VI.DHS.VI.cr.Rout: downloaded/ngcr6afl.sav
converted/Nigeria_VI.DHS.VI.gps.Rout: downloaded/ngge6afl.dbf
converted/Pakistan_II.DHS.II.women.Rout: downloaded/pkir21fl.sav
converted/Pakistan_II.DHS.II.men.Rout: downloaded/pkmr21fl.sav
converted/Pakistan_II.DHS.II.cr.Rout: downloaded/pkcr21fl.sav
converted/Pakistan_V.DHS.V.women.Rout: downloaded/pkir52fl.sav
converted/Pakistan_V.DHS.V.gps.Rout: downloaded/pkge51fl.dbf
converted/Pakistan_VI.DHS.VI.women.Rout: downloaded/pkir61fl.sav
converted/Pakistan_VI.DHS.VI.men.Rout: downloaded/pkmr61fl.sav
converted/Paraguay_II.DHS.II.women.Rout: downloaded/pyir21fl.sav
converted/Peru_I.DHS.I.women.Rout: downloaded/peir01fl.sav
converted/Peru_II.DHS.II.women.Rout: downloaded/peir21fl.sav
converted/Peru_III.DHS.III.women.Rout: downloaded/peir31fl.sav
converted/Peru_III.DHS.III.men.Rout: downloaded/pemr31fl.sav
converted/Peru_III.DHS.III.cr.Rout: downloaded/pecr31fl.sav
converted/Peru_IV.DHS.IV.women.Rout: downloaded/peir41fl.sav
converted/Peru_IV.DHS.IV.gps.Rout: downloaded/pege44fl.dbf
converted/Philippines_III.DHS.II.women.Rout: downloaded/phir31fl.sav
converted/Philippines_III.DHS.III.women.Rout: downloaded/phir3bfl.sav
converted/Philippines_IV.DHS.IV.women.Rout: downloaded/phir41fl.sav
converted/Philippines_IV.DHS.IV.men.Rout: downloaded/phmr41fl.sav
converted/Philippines_IV.DHS.IV.cr.Rout: downloaded/phcr41fl.sav
converted/Philippines_IV.DHS.IV.gps.Rout: downloaded/phge43fl.dbf
converted/Philippines_V.DHS.V.women.Rout: downloaded/phir52fl.sav
converted/Philippines_V.DHS.V.gps.Rout: downloaded/phge52fl.dbf
converted/Philippines_VI.DHS.VI.women.Rout: downloaded/phir61fl.sav
converted/Rwanda_II.DHS.II.women.Rout: downloaded/rwir21fl.sav
converted/Rwanda_II.DHS.II.men.Rout: downloaded/rwmr21fl.sav
converted/Rwanda_II.DHS.II.cr.Rout: downloaded/rwcr21fl.sav
converted/Rwanda_IV.DHS.IV.women.Rout: downloaded/rwir41fl.sav
converted/Rwanda_IV.DHS.IV.men.Rout: downloaded/rwmr41fl.sav
converted/Rwanda_IV.DHS.IV.cr.Rout: downloaded/rwcr41fl.sav
converted/Rwanda_V.DHS.IV.women.Rout: downloaded/rwir53fl.sav
converted/Rwanda_V.DHS.IV.men.Rout: downloaded/rwmr53fl.sav
converted/Rwanda_V.DHS.IV.cr.Rout: downloaded/rwcr53fl.sav
converted/Rwanda_V.DHS.IV.gps.Rout: downloaded/rwge54fl.dbf
converted/Rwanda_VI.DHS.VI.women.Rout: downloaded/rwir61fl.sav
converted/Rwanda_VI.DHS.VI.men.Rout: downloaded/rwmr61fl.sav
converted/Rwanda_VI.DHS.VI.cr.Rout: downloaded/rwcr61fl.sav
converted/Rwanda_VI.DHS.VI.gps.Rout: downloaded/rwge61fl.dbf
converted/Rwanda_VII.DHS.VI.women.Rout: downloaded/rwir70fl.sav
converted/Rwanda_VII.DHS.VI.men.Rout: downloaded/rwmr70fl.sav
converted/Rwanda_VII.DHS.VI.cr.Rout: downloaded/rwcr70fl.sav
converted/Rwanda_VII.DHS.VI.gps.Rout: downloaded/rwge71fl.dbf
converted/Sao_Tome_V.DHS.V.women.Rout: downloaded/stir50fl.sav
converted/Sao_Tome_V.DHS.V.men.Rout: downloaded/stmr50fl.sav
converted/Sao_Tome_V.DHS.V.cr.Rout: downloaded/stcr50fl.sav
converted/Senegal_I.DHS.I.women.Rout: downloaded/snir02fl.sav
converted/Senegal_II.DHS.II.women.Rout: downloaded/snir21fl.sav
converted/Senegal_II.DHS.II.men.Rout: downloaded/snmr21fl.sav
converted/Senegal_II.DHS.II.cr.Rout: downloaded/sncr21fl.sav
converted/Senegal_II.DHS.II.gps.Rout: downloaded/snge23fl.dbf
converted/Senegal_III.DHS.II.women.Rout: downloaded/snir32fl.sav
converted/Senegal_III.DHS.II.men.Rout: downloaded/snmr31fl.sav
converted/Senegal_III.DHS.II.cr.Rout: downloaded/sncr31fl.sav
converted/Senegal_III.DHS.II.gps.Rout: downloaded/snge32fl.dbf
converted/Senegal_IV.DHS.IV.women.Rout: downloaded/snir4hfl.sav
converted/Senegal_IV.DHS.IV.men.Rout: downloaded/snmr4hfl.sav
converted/Senegal_IV.DHS.IV.cr.Rout: downloaded/sncr4hfl.sav
converted/Senegal_IV.DHS.IV.gps.Rout: downloaded/snge4bfl.dbf
converted/Senegal_VI.DHS.VI.women.Rout: downloaded/snir61fl.sav
converted/Senegal_VI.DHS.VI.men.Rout: downloaded/snmr61fl.sav
converted/Senegal_VI.DHS.VI.cr.Rout: downloaded/sncr61fl.sav
converted/Senegal_VI.DHS.VI.gps.Rout: downloaded/snge61fl.dbf
converted/Sierra_Leone_V.DHS.V.women.Rout: downloaded/slir51fl.sav
converted/Sierra_Leone_V.DHS.V.men.Rout: downloaded/slmr51fl.sav
converted/Sierra_Leone_V.DHS.V.cr.Rout: downloaded/slcr51fl.sav
converted/Sierra_Leone_V.DHS.V.gps.Rout: downloaded/slge53fl.dbf
converted/Sierra_Leone_VI.DHS.VI.women.Rout: downloaded/slir61fl.sav
converted/Sierra_Leone_VI.DHS.VI.men.Rout: downloaded/slmr61fl.sav
converted/Sierra_Leone_VI.DHS.VI.cr.Rout: downloaded/slcr61fl.sav
converted/Sierra_Leone_VI.DHS.VI.gps.Rout: downloaded/slge61fl.dbf
converted/South_Africa_III.DHS.III.women.Rout: downloaded/zair31fl.sav
converted/Sri_Lanka_I.DHS.I.women.Rout: downloaded/lkir02fl.sav
converted/Sudan_I.DHS.I.women.Rout: downloaded/sdir02fl.sav
converted/Swaziland_V.DHS.V.women.Rout: downloaded/szir51fl.sav
converted/Swaziland_V.DHS.V.men.Rout: downloaded/szmr51fl.sav
converted/Swaziland_V.DHS.V.cr.Rout: downloaded/szcr51fl.sav
converted/Swaziland_V.DHS.V.gps.Rout: downloaded/szge53fl.dbf
converted/Tajikistan_VI.DHS.VI.women.Rout: downloaded/tjir61fl.sav
converted/Tajikistan_VI.DHS.VI.gps.Rout: downloaded/tjge61fl.dbf
converted/Tanzania_II.DHS.II.women.Rout: downloaded/tzir21fl.sav
converted/Tanzania_II.DHS.II.men.Rout: downloaded/tzmr21fl.sav
converted/Tanzania_II.DHS.II.cr.Rout: downloaded/tzcr21fl.sav
converted/Tanzania_III.DHS.III.women.Rout: downloaded/tzir3afl.sav
converted/Tanzania_III.DHS.III.men.Rout: downloaded/tzmr3afl.sav
converted/Tanzania_III.DHS.III.cr.Rout: downloaded/tzcr3afl.sav
converted/Tanzania_IVb.DHS.IV.women.Rout: downloaded/tzir41fl.sav
converted/Tanzania_IVb.DHS.IV.men.Rout: downloaded/tzmr41fl.sav
converted/Tanzania_IVb.DHS.IV.cr.Rout: downloaded/tzcr41fl.sav
converted/Tanzania_IVb.DHS.IV.gps.Rout: downloaded/tzge43fl.dbf
converted/Tanzania_IV.AIS.V.women.Rout: downloaded/tzir4afl.sav
converted/Tanzania_IV.AIS.V.gps.Rout: downloaded/tzge4cfl.dbf
converted/Tanzania_IVa.DHS.IV.women.Rout: downloaded/tzir4ifl.sav
converted/Tanzania_IVa.DHS.IV.men.Rout: downloaded/tzmr4ifl.sav
converted/Tanzania_IVa.DHS.IV.cr.Rout: downloaded/tzcr4ifl.sav
converted/Tanzania_V.AIS.V.women.Rout: downloaded/tzir51fl.sav
converted/Tanzania_V.AIS.V.gps.Rout: downloaded/tzge52fl.dbf
converted/Tanzania_VI.DHS.V.women.Rout: downloaded/tzir63fl.sav
converted/Tanzania_VI.DHS.V.men.Rout: downloaded/tzmr61fl.sav
converted/Tanzania_VI.DHS.V.cr.Rout: downloaded/tzcr63fl.sav
converted/Tanzania_VI.DHS.V.gps.Rout: downloaded/tzob61..tzge61fl.dbf
converted/Tanzania_VI.AIS.VI.women.Rout: downloaded/tzir6afl.sav
converted/Tanzania_VI.AIS.VI.gps.Rout: downloaded/tzge6afl.dbf
converted/Tanzania_VII.DHS.VII.women.Rout: downloaded/tzir7hfl.sav
converted/Tanzania_VII.DHS.VII.men.Rout: downloaded/tzmr7hfl.sav
converted/Tanzania_VII.DHS.VII.cr.Rout: downloaded/tzcr7hfl.sav
converted/Tanzania_VII.DHS.VII.gps.Rout: downloaded/tzge7afl.dbf
converted/Thailand_I.DHS.I.women.Rout: downloaded/thir01fl.sav
converted/Timor-Leste_VI.DHS.V.women.Rout: downloaded/tlir61fl.sav
converted/Timor-Leste_VI.DHS.V.men.Rout: downloaded/tlmr61fl.sav
converted/Timor-Leste_VI.DHS.V.cr.Rout: downloaded/tlcr61fl.sav
converted/Timor-Leste_VI.DHS.V.gps.Rout: downloaded/tlge62fl.dbf
converted/Togo_I.DHS.I.women.Rout: downloaded/tgir01fl.sav
converted/Togo_I.DHS.I.gps.Rout: downloaded/tgge03fl.dbf
converted/Togo_III.DHS.III.women.Rout: downloaded/tgir31fl.sav
converted/Togo_III.DHS.III.men.Rout: downloaded/tgmr31fl.sav
converted/Togo_III.DHS.III.cr.Rout: downloaded/tgcr31fl.sav
converted/Togo_III.DHS.III.gps.Rout: downloaded/tgge32fl.dbf
converted/Togo_VI.DHS.VI.women.Rout: downloaded/tgir61fl.sav
converted/Togo_VI.DHS.VI.men.Rout: downloaded/tgmr61fl.sav
converted/Togo_VI.DHS.VI.cr.Rout: downloaded/tgcr61fl.sav
converted/Togo_VI.DHS.VI.gps.Rout: downloaded/tgge62fl.dbf
converted/Trinidad_I.DHS.I.women.Rout: downloaded/ttir01fl.sav
converted/Tunisia_I.DHS.I.women.Rout: downloaded/tnir02fl.sav
converted/Turkey_III.DHS.II.women.Rout: downloaded/trir31fl.sav
converted/Turkey_IV.DHS.III.women.Rout: downloaded/trir41fl.sav
converted/Turkey_IV.DHS.III.men.Rout: downloaded/trmr41fl.sav
converted/Turkey_IV.DHS.III.cr.Rout: downloaded/trcr41fl.sav
converted/Turkey_IV.DHS.IV.women.Rout: downloaded/trir4afl.sav
converted/Uganda_I.DHS.I.women.Rout: downloaded/ugir01fl.sav
converted/Uganda_III.DHS.III.women.Rout: downloaded/ugir33fl.sav
converted/Uganda_III.DHS.III.men.Rout: downloaded/ugmr33fl.sav
converted/Uganda_III.DHS.III.cr.Rout: downloaded/ugcr33fl.sav
converted/Uganda_IV.DHS.IV.women.Rout: downloaded/ugir41fl.sav
converted/Uganda_IV.DHS.IV.men.Rout: downloaded/ugmr41fl.sav
converted/Uganda_IV.DHS.IV.cr.Rout: downloaded/ugcr41fl.sav
converted/Uganda_IV.DHS.IV.gps.Rout: downloaded/ugge43fl.dbf
converted/Uganda_V.DHS.V.women.Rout: downloaded/ugir52fl.sav
converted/Uganda_V.DHS.V.men.Rout: downloaded/ugmr52fl.sav
converted/Uganda_V.DHS.V.cr.Rout: downloaded/ugcr52fl.sav
converted/Uganda_V.DHS.V.gps.Rout: downloaded/ugge53fl.dbf
converted/Uganda_VI.DHS.VI.women.Rout: downloaded/ugir6a..ugir60fl.sav
converted/Uganda_VI.DHS.VI.men.Rout: downloaded/ugmr60fl.sav
converted/Uganda_VI.DHS.VI.cr.Rout: downloaded/ugcr60fl.sav
converted/Uganda_VI.DHS.VI.gps.Rout: downloaded/ugge6a..ugge61fl.dbf
converted/Ukraine_V.DHS.V.women.Rout: downloaded/uair51fl.sav
converted/Ukraine_V.DHS.V.men.Rout: downloaded/uamr51fl.sav
converted/Ukraine_V.DHS.V.cr.Rout: downloaded/uacr51fl.sav
converted/Uzbekistan_III.DHS.III.women.Rout: downloaded/uzir31fl.sav
converted/Vietnam_III.DHS.III.women.Rout: downloaded/vnir31fl.sav
converted/Vietnam_IV.DHS.IV.women.Rout: downloaded/vnir41fl.sav
converted/Vietnam_V.AIS.V.women.Rout: downloaded/vnir52fl.sav
converted/Yemen_II.DHS.II.women.Rout: downloaded/yeir21fl.sav
converted/Yemen_VI.DHS.VI.women.Rout: downloaded/yeir61fl.sav
converted/Zambia_II.DHS.II.women.Rout: downloaded/zmir21fl.sav
converted/Zambia_III.DHS.III.women.Rout: downloaded/zmir31fl.sav
converted/Zambia_III.DHS.III.men.Rout: downloaded/zmmr31fl.sav
converted/Zambia_III.DHS.III.cr.Rout: downloaded/zmcr31fl.sav
converted/Zambia_IV.DHS.IV.women.Rout: downloaded/zmir42fl.sav
converted/Zambia_IV.DHS.IV.men.Rout: downloaded/zmmr41fl.sav
converted/Zambia_IV.DHS.IV.cr.Rout: downloaded/zmcr42fl.sav
converted/Zambia_V.DHS.V.women.Rout: downloaded/zmir51fl.sav
converted/Zambia_V.DHS.V.men.Rout: downloaded/zmmr51fl.sav
converted/Zambia_V.DHS.V.cr.Rout: downloaded/zmcr51fl.sav
converted/Zambia_V.DHS.V.gps.Rout: downloaded/zmge52fl.dbf
converted/Zambia_VI.DHS.VI.women.Rout: downloaded/zmir61fl.sav
converted/Zambia_VI.DHS.VI.men.Rout: downloaded/zmmr61fl.sav
converted/Zambia_VI.DHS.VI.cr.Rout: downloaded/zmcr61fl.sav
converted/Zambia_VI.DHS.VI.gps.Rout: downloaded/zmge61fl.dbf
converted/Zimbabwe_I.DHS.I.women.Rout: downloaded/zwir01fl.sav
converted/Zimbabwe_III.DHS.III.women.Rout: downloaded/zwir31fl.sav
converted/Zimbabwe_III.DHS.III.men.Rout: downloaded/zwmr31fl.sav
converted/Zimbabwe_III.DHS.III.cr.Rout: downloaded/zwcr31fl.sav
converted/Zimbabwe_IV.DHS.IV.women.Rout: downloaded/zwir42fl.sav
converted/Zimbabwe_IV.DHS.IV.men.Rout: downloaded/zwmr41fl.sav
converted/Zimbabwe_IV.DHS.IV.cr.Rout: downloaded/zwcr41fl.sav
converted/Zimbabwe_IV.DHS.IV.gps.Rout: downloaded/zwge42fl.dbf
converted/Zimbabwe_V.DHS.V.women.Rout: downloaded/zwir52fl.sav
converted/Zimbabwe_V.DHS.V.men.Rout: downloaded/zwmr52fl.sav
converted/Zimbabwe_V.DHS.V.cr.Rout: downloaded/zwcr52fl.sav
converted/Zimbabwe_V.DHS.V.gps.Rout: downloaded/zwge52fl.dbf
converted/Zimbabwe_VI.DHS.VI.women.Rout: downloaded/zwir62fl.sav
converted/Zimbabwe_VI.DHS.VI.men.Rout: downloaded/zwmr62fl.sav
converted/Zimbabwe_VI.DHS.VI.cr.Rout: downloaded/zwcr62fl.sav
converted/Zimbabwe_VI.DHS.VI.gps.Rout: downloaded/zwge61fl.dbf
converted/Zimbabwe_VII.DHS.VII.women.Rout: downloaded/zwir70fl.sav
converted/Zimbabwe_VII.DHS.VII.men.Rout: downloaded/zwmr70fl.sav
converted/Zimbabwe_VII.DHS.VII.cr.Rout: downloaded/zwcr70fl.sav
converted/Zimbabwe_VII.DHS.VII.gps.Rout: downloaded/zwge71fl.dbf
